development:
  adapter: postgresql
  encoding: unicode
  database: teamzu_development
  pool: 5
  username: austin_schneider
    
test: &test
  adapter: postgresql
  encoding: unicode
  database: teamzu_test
  pool: 5
  username: austin_schneider

cucumber:
  <<: *test

staging:
  adapter: postgresql
  encoding: unicode
  database: teamzu_staging
  pool: 5
  username: austin_schneider

production:
  adapter: postgresql
  encoding: unicode
  database: teamzu_production
  pool: 5
  username: austin_schneider